export const RECIPE_POOL = [
  {
    name: "Chicken Alfredo",
    servings: 4,
    ingredients: [
      { name: "chicken", quantity: 1, unit: "lb" },
      { name: "pasta", quantity: 12, unit: "oz" },
      { name: "cream", quantity: 1.5, unit: "cups" },
      { name: "garlic", quantity: 3, unit: "cloves" },
      { name: "parmesan", quantity: 0.75, unit: "cup" },
    ],
    dietaryTags: [],
    steps: [
      "Boil pasta in salted water until al dente, then drain.",
      "Season and pan-sear chicken until golden and cooked through, then slice.",
      "Saute garlic, add cream, and simmer until slightly thickened.",
      "Stir in parmesan, toss with pasta and chicken, and serve hot.",
    ],
  },
  {
    name: "Omelette",
    servings: 2,
    ingredients: [
      { name: "eggs", quantity: 4, unit: "large" },
      { name: "cheese", quantity: 0.5, unit: "cup" },
      { name: "milk", quantity: 0.25, unit: "cup" },
      { name: "onion", quantity: 0.25, unit: "whole" },
      { name: "bell pepper", quantity: 0.5, unit: "whole" },
    ],
    dietaryTags: ["vegetarian", "gluten-free"],
    steps: [
      "Whisk eggs with milk, salt, and pepper until smooth.",
      "Saute onion and bell pepper in a nonstick pan until softened.",
      "Pour in eggs and cook on low heat until mostly set.",
      "Add cheese, fold the omelette, and cook 1 more minute.",
    ],
  },
  {
    name: "Pasta Primavera",
    servings: 4,
    ingredients: [
      { name: "pasta", quantity: 12, unit: "oz" },
      { name: "zucchini", quantity: 1, unit: "whole" },
      { name: "bell pepper", quantity: 1, unit: "whole" },
      { name: "broccoli", quantity: 2, unit: "cups" },
      { name: "olive oil", quantity: 2, unit: "tbsp" },
    ],
    dietaryTags: ["vegetarian"],
    steps: [
      "Cook pasta until al dente and reserve a little pasta water.",
      "Saute zucchini, bell pepper, and broccoli in olive oil.",
      "Toss cooked pasta with vegetables and a splash of pasta water.",
      "Season with salt and pepper, then serve immediately.",
    ],
  },
  {
    name: "Caprese Salad",
    servings: 2,
    ingredients: [
      { name: "tomato", quantity: 2, unit: "whole" },
      { name: "basil", quantity: 0.5, unit: "cup" },
      { name: "mozzarella", quantity: 8, unit: "oz" },
      { name: "olive oil", quantity: 1.5, unit: "tbsp" },
    ],
    dietaryTags: ["vegetarian", "gluten-free"],
    steps: [
      "Slice tomatoes and mozzarella into even rounds.",
      "Layer tomato, mozzarella, and basil leaves on a plate.",
      "Drizzle olive oil evenly over the salad.",
      "Season with salt and pepper before serving.",
    ],
  },
  {
    name: "Fried Rice",
    servings: 4,
    ingredients: [
      { name: "rice", quantity: 4, unit: "cups cooked" },
      { name: "egg", quantity: 2, unit: "large" },
      { name: "carrot", quantity: 1, unit: "whole" },
      { name: "peas", quantity: 1, unit: "cup" },
      { name: "soy sauce", quantity: 2, unit: "tbsp" },
    ],
    dietaryTags: ["dairy-free"],
    steps: [
      "Scramble egg in a hot pan and set aside.",
      "Saute carrot and peas until tender.",
      "Add cold cooked rice and stir-fry until heated through.",
      "Mix in egg and soy sauce, then cook for 1 to 2 minutes.",
    ],
  },
  {
    name: "Grilled Cheese",
    servings: 1,
    ingredients: [
      { name: "bread", quantity: 2, unit: "slices" },
      { name: "cheese", quantity: 2, unit: "slices" },
      { name: "butter", quantity: 1, unit: "tbsp" },
    ],
    dietaryTags: ["vegetarian"],
    steps: [
      "Butter the outside of two bread slices.",
      "Place cheese between slices with buttered sides facing out.",
      "Cook on medium-low heat until the first side is golden.",
      "Flip and cook until cheese melts and bread is crisp.",
    ],
  },
  {
    name: "Tacos",
    servings: 4,
    ingredients: [
      { name: "tortilla", quantity: 8, unit: "small" },
      { name: "ground beef", quantity: 1, unit: "lb" },
      { name: "cheese", quantity: 1, unit: "cup" },
      { name: "lettuce", quantity: 2, unit: "cups" },
      { name: "tomato", quantity: 2, unit: "whole" },
    ],
    dietaryTags: [],
    steps: [
      "Cook ground beef in a skillet until browned and fully cooked.",
      "Warm tortillas in a dry pan or microwave.",
      "Fill tortillas with beef, lettuce, and tomato.",
      "Top with cheese and serve right away.",
    ],
  },
  {
    name: "Pancakes",
    servings: 4,
    ingredients: [
      { name: "flour", quantity: 1.5, unit: "cups" },
      { name: "egg", quantity: 1, unit: "large" },
      { name: "milk", quantity: 1.25, unit: "cups" },
      { name: "sugar", quantity: 2, unit: "tbsp" },
      { name: "baking powder", quantity: 2, unit: "tsp" },
    ],
    dietaryTags: ["vegetarian"],
    steps: [
      "Whisk flour, sugar, and baking powder in a bowl.",
      "Mix in egg and milk until batter is smooth.",
      "Pour batter onto a hot greased skillet.",
      "Flip when bubbles form and cook until both sides are golden.",
    ],
  },
  {
    name: "BLT Sandwich",
    servings: 2,
    ingredients: [
      { name: "bread", quantity: 4, unit: "slices" },
      { name: "bacon", quantity: 6, unit: "slices" },
      { name: "lettuce", quantity: 4, unit: "leaves" },
      { name: "tomato", quantity: 1, unit: "whole" },
      { name: "mayonnaise", quantity: 2, unit: "tbsp" },
    ],
    dietaryTags: ["dairy-free"],
    steps: [
      "Cook bacon until crispy and drain on paper towels.",
      "Toast bread slices to your preferred level.",
      "Spread mayonnaise on the toast.",
      "Layer bacon, lettuce, and tomato, then close and slice.",
    ],
  },
  {
    name: "Veggie Stir Fry",
    servings: 4,
    ingredients: [
      { name: "broccoli", quantity: 2, unit: "cups" },
      { name: "carrot", quantity: 2, unit: "whole" },
      { name: "bell pepper", quantity: 1, unit: "whole" },
      { name: "soy sauce", quantity: 2, unit: "tbsp" },
      { name: "rice", quantity: 3, unit: "cups cooked" },
    ],
    dietaryTags: ["vegan", "vegetarian", "dairy-free"],
    steps: [
      "Heat oil in a wok and add broccoli, carrot, and bell pepper.",
      "Stir-fry on high heat until vegetables are tender-crisp.",
      "Add soy sauce and toss to coat evenly.",
      "Serve over warm rice.",
    ],
  },
  {
    name: "Chickpea Curry",
    servings: 4,
    ingredients: [
      { name: "chickpeas", quantity: 2, unit: "cans" },
      { name: "tomato", quantity: 2, unit: "whole" },
      { name: "onion", quantity: 1, unit: "whole" },
      { name: "garlic", quantity: 3, unit: "cloves" },
      { name: "coconut milk", quantity: 1, unit: "can" },
    ],
    dietaryTags: ["vegan", "vegetarian", "dairy-free", "gluten-free"],
    steps: [
      "Saute onion and garlic until fragrant.",
      "Add tomato and cook down into a thick base.",
      "Stir in chickpeas and coconut milk, then simmer.",
      "Cook until flavors combine and serve with rice.",
    ],
  },
  {
    name: "Quinoa Bowl",
    servings: 4,
    ingredients: [
      { name: "quinoa", quantity: 1.5, unit: "cups dry" },
      { name: "black beans", quantity: 1.5, unit: "cups" },
      { name: "avocado", quantity: 2, unit: "whole" },
      { name: "corn", quantity: 1.5, unit: "cups" },
      { name: "lime", quantity: 1, unit: "whole" },
    ],
    dietaryTags: ["vegan", "vegetarian", "dairy-free", "gluten-free"],
    steps: [
      "Cook quinoa according to package directions.",
      "Warm black beans and corn in a small pan.",
      "Assemble bowls with quinoa, beans, corn, and sliced avocado.",
      "Finish with lime juice, salt, and pepper.",
    ],
  },
  {
    name: "Salmon and Veggies",
    servings: 2,
    ingredients: [
      { name: "salmon", quantity: 1, unit: "lb" },
      { name: "broccoli", quantity: 3, unit: "cups" },
      { name: "lemon", quantity: 1, unit: "whole" },
      { name: "olive oil", quantity: 1.5, unit: "tbsp" },
      { name: "garlic", quantity: 2, unit: "cloves" },
    ],
    dietaryTags: ["dairy-free", "gluten-free"],
    steps: [
      "Season salmon with garlic, salt, pepper, and olive oil.",
      "Roast salmon and broccoli on a sheet pan at 425 F.",
      "Cook until salmon flakes easily and broccoli is tender.",
      "Squeeze lemon over the tray before serving.",
    ],
  },
  {
    name: "Turkey Lettuce Wraps",
    servings: 4,
    ingredients: [
      { name: "ground turkey", quantity: 1, unit: "lb" },
      { name: "lettuce", quantity: 10, unit: "leaves" },
      { name: "carrot", quantity: 1, unit: "whole" },
      { name: "soy sauce", quantity: 1.5, unit: "tbsp" },
      { name: "ginger", quantity: 1, unit: "tbsp" },
    ],
    dietaryTags: ["dairy-free", "gluten-free"],
    steps: [
      "Cook ground turkey in a skillet until fully browned.",
      "Add grated carrot, ginger, and soy sauce.",
      "Simmer for 2 to 3 minutes until flavors combine.",
      "Spoon into lettuce leaves and serve.",
    ],
  },
  {
    name: "Greek Yogurt Parfait",
    servings: 2,
    ingredients: [
      { name: "greek yogurt", quantity: 2, unit: "cups" },
      { name: "berries", quantity: 1.5, unit: "cups" },
      { name: "honey", quantity: 2, unit: "tbsp" },
      { name: "granola", quantity: 1, unit: "cup" },
    ],
    dietaryTags: ["vegetarian"],
    steps: [
      "Spoon Greek yogurt into a glass or bowl.",
      "Add a layer of berries.",
      "Drizzle honey over the top.",
      "Finish with granola just before eating.",
    ],
  },
  {
    name: "Tofu Scramble",
    servings: 3,
    ingredients: [
      { name: "tofu", quantity: 14, unit: "oz" },
      { name: "onion", quantity: 0.5, unit: "whole" },
      { name: "bell pepper", quantity: 0.5, unit: "whole" },
      { name: "spinach", quantity: 2, unit: "cups" },
      { name: "turmeric", quantity: 1, unit: "tsp" },
    ],
    dietaryTags: ["vegan", "vegetarian", "dairy-free", "gluten-free"],
    steps: [
      "Crumble tofu and season with turmeric, salt, and pepper.",
      "Saute onion and bell pepper until softened.",
      "Add tofu and cook while stirring until heated through.",
      "Fold in spinach and cook until wilted.",
    ],
  },
  {
    name: "Lentil Soup",
    servings: 6,
    ingredients: [
      { name: "lentils", quantity: 1.5, unit: "cups dry" },
      { name: "carrot", quantity: 2, unit: "whole" },
      { name: "celery", quantity: 2, unit: "stalks" },
      { name: "onion", quantity: 1, unit: "whole" },
      { name: "vegetable broth", quantity: 6, unit: "cups" },
    ],
    dietaryTags: ["vegan", "vegetarian", "dairy-free", "gluten-free"],
    steps: [
      "Saute onion, carrot, and celery until softened.",
      "Add lentils and vegetable broth.",
      "Bring to a boil, then simmer until lentils are tender.",
      "Adjust seasoning and serve warm.",
    ],
  },
  {
    name: "Shrimp Tacos",
    servings: 4,
    ingredients: [
      { name: "shrimp", quantity: 1, unit: "lb" },
      { name: "tortilla", quantity: 8, unit: "small" },
      { name: "cabbage", quantity: 2, unit: "cups shredded" },
      { name: "lime", quantity: 1, unit: "whole" },
      { name: "cilantro", quantity: 0.5, unit: "cup" },
    ],
    dietaryTags: ["dairy-free"],
    steps: [
      "Season shrimp and saute until pink and cooked through.",
      "Warm tortillas in a skillet.",
      "Fill tortillas with shrimp and shredded cabbage.",
      "Top with cilantro and fresh lime juice.",
    ],
  },
  {
    name: "Veggie Burrito Bowl",
    servings: 4,
    ingredients: [
      { name: "rice", quantity: 3, unit: "cups cooked" },
      { name: "black beans", quantity: 1.5, unit: "cups" },
      { name: "corn", quantity: 1, unit: "cup" },
      { name: "avocado", quantity: 1, unit: "whole" },
      { name: "salsa", quantity: 1, unit: "cup" },
    ],
    dietaryTags: ["vegan", "vegetarian", "dairy-free", "gluten-free"],
    steps: [
      "Cook rice and place it in serving bowls.",
      "Warm black beans and corn together.",
      "Add beans, corn, avocado, and salsa over rice.",
      "Season and serve with lime if desired.",
    ],
  },
  {
    name: "Egg Fried Quinoa",
    servings: 4,
    ingredients: [
      { name: "quinoa", quantity: 3, unit: "cups cooked" },
      { name: "egg", quantity: 2, unit: "large" },
      { name: "peas", quantity: 1, unit: "cup" },
      { name: "carrot", quantity: 1, unit: "whole" },
      { name: "soy sauce", quantity: 1.5, unit: "tbsp" },
    ],
    dietaryTags: ["vegetarian", "dairy-free", "gluten-free"],
    steps: [
      "Cook quinoa and let it cool slightly.",
      "Scramble egg in a pan and set aside.",
      "Stir-fry peas and carrot, then add quinoa.",
      "Return egg to pan, add soy sauce, and mix well.",
    ],
  },
  {
    name: "Baked Potato Bar",
    servings: 4,
    ingredients: [
      { name: "potato", quantity: 4, unit: "whole" },
      { name: "cheddar", quantity: 1, unit: "cup" },
      { name: "green onion", quantity: 0.5, unit: "cup" },
      { name: "sour cream", quantity: 0.75, unit: "cup" },
      { name: "beans", quantity: 1.5, unit: "cups" },
    ],
    dietaryTags: ["vegetarian", "gluten-free"],
    steps: [
      "Bake potatoes at 400 F until fork tender.",
      "Warm beans and prepare toppings.",
      "Split potatoes open and fluff the inside.",
      "Top with cheddar, sour cream, beans, and green onion.",
    ],
  },
  {
    name: "Peanut Noodles",
    servings: 4,
    ingredients: [
      { name: "noodles", quantity: 12, unit: "oz" },
      { name: "peanut butter", quantity: 0.33, unit: "cup" },
      { name: "soy sauce", quantity: 2, unit: "tbsp" },
      { name: "garlic", quantity: 2, unit: "cloves" },
      { name: "green onion", quantity: 0.5, unit: "cup" },
    ],
    dietaryTags: ["vegan", "vegetarian", "dairy-free"],
    steps: [
      "Cook noodles and reserve a little noodle water.",
      "Whisk peanut butter, soy sauce, garlic, and warm water into a sauce.",
      "Toss noodles with sauce until coated.",
      "Garnish with sliced green onion and serve.",
    ],
  },
  {
    name: "Chicken Fajita Bowl",
    servings: 4,
    ingredients: [
      { name: "chicken", quantity: 1, unit: "lb" },
      { name: "rice", quantity: 3, unit: "cups cooked" },
      { name: "bell pepper", quantity: 2, unit: "whole" },
      { name: "onion", quantity: 1, unit: "whole" },
      { name: "lime", quantity: 1, unit: "whole" },
    ],
    dietaryTags: ["dairy-free", "gluten-free"],
    steps: [
      "Season and cook chicken until done, then slice.",
      "Saute bell pepper and onion until lightly charred.",
      "Build bowls with rice, chicken, and vegetables.",
      "Finish with fresh lime juice.",
    ],
  },
  {
    name: "Tomato Basil Soup",
    servings: 4,
    ingredients: [
      { name: "tomato", quantity: 6, unit: "whole" },
      { name: "basil", quantity: 0.75, unit: "cup" },
      { name: "garlic", quantity: 3, unit: "cloves" },
      { name: "onion", quantity: 1, unit: "whole" },
      { name: "vegetable broth", quantity: 4, unit: "cups" },
    ],
    dietaryTags: ["vegan", "vegetarian", "dairy-free", "gluten-free"],
    steps: [
      "Saute onion and garlic until soft and fragrant.",
      "Add tomato and vegetable broth, then simmer.",
      "Blend until smooth and return to low heat.",
      "Stir in basil, season, and serve warm.",
    ],
  },
];

export const QUICK_ADD_INGREDIENTS = [
  "rice",
  "pasta",
  "egg",
  "eggs",
  "milk",
  "cheese",
  "bread",
  "chicken",
  "ground beef",
  "salmon",
  "tofu",
  "chickpeas",
  "black beans",
  "potato",
  "broccoli",
  "spinach",
  "tomato",
  "onion",
  "garlic",
  "bell pepper",
  "carrot",
  "avocado",
  "quinoa",
  "lentils",
  "yogurt",
  "olive oil",
];
